/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CREARBASESDEDATOS.java
 *
 * Created on 28/06/2010, 09:45:39 AM
 */

/**
 *
 * @author simpus
 */
public class CREARBASESDEDATOS extends javax.swing.JDialog {
    String mensaje="";
    ServidorMysql basededatos;
    /** Creates new form CREARBASESDEDATOS */
    public CREARBASESDEDATOS(java.awt.Frame parent, boolean t) {
        super(parent,t);
        basededatos = new ServidorMysql();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("INICIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("<HTML>SE CREARAN LAS TABLAS CORRESPONDIENTES PARA <BR>EL CORRECTO FUNCIONAMIENTO DEL SISTEMA.");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(mensaje);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(basededatos.coneccion("localhost")){
            mensaje += "Se conectó correctamente a la base de datos\n";
         jTextArea1.setText(mensaje);
        }
        else
        {
            mensaje += "Error al conectarse a la base de datos\n";
             jTextArea1.setText(mensaje);
            //return;
        }
       
        if(basededatos.operacion("CREATE TABLE dinero(m50c float(10)," +
                " m1 int(10), m2 int(10), m5 int(10), m10 int(10), m20 int(10), " +
                " b20 int(10), b50 int(10), b100 int(10), b200 int(10)," +
                " b500 int(10), b1000 int(10))"))
        {
            mensaje += "Se creó tabla dinero\n";
             jTextArea1.setText(mensaje);
        }
        else
        {
            mensaje += "Error al crear tabla dinero\n";
             jTextArea1.setText(mensaje);
            //return;
      }

        if(!basededatos.operacion("INSERT INTO dinero values(0,0,0,0,0,0,0,0,0,0,0,0)"))
        {
              mensaje += "Error al insertar datos en la tabla\n";
             jTextArea1.setText(mensaje);
        }
        else
        {
            mensaje += "Se insertaron los datos satisfactoriamente\n";
             jTextArea1.setText(mensaje);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
