
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal.java
 *
 * Created on 14/07/2010, 09:51:58 PM
 */

/**
 *
 * @author simpus
 */
public class Principal extends javax.swing.JFrame {

    /** Creates new form Principal */
    double TOTAL;
    public Principal() {
        ServidorMysql servidor = new ServidorMysql();
            if(!servidor.coneccion("localhost"))
            {
                int resultado = JOptionPane.showConfirmDialog(null, "NO SE PUEDE CONECTAR A LA BASE DE DATOS\n" +
                        "¿ES LA PRIMERA VEZ QUE SE EJECUTA ESTE PROGRAMA?","ERROR",JOptionPane.YES_NO_OPTION);
                if(resultado == JOptionPane.YES_OPTION)
                {
                    JOptionPane.showMessageDialog(null, "INSTALE EL PROGRAMA MYSQL 5.1 Y CREE UNA BASE DE DATOS\n" +
                            "CON EL NOMBRE DE << retiros >> Y VUELVA A EJECUTAR EL PROGRAMA");
                    System.exit(0);
                }
                else
                     System.exit(0);
            }
            if(servidor.consulta("select * from dinero"))
            {
                 initComponents();
                 calcularTotal();
            }
            else
            {
                 int resultado = JOptionPane.showConfirmDialog(null, "NO SE HA DETECTADO LA TABLA << dinero >>\n" +
                        "¿DESEA QUE SE CREE UNA TABLA NUEVA PARA ESTE PROGRAMA?","ERROR",JOptionPane.YES_NO_OPTION);
                if(resultado == JOptionPane.YES_OPTION)
                {
                       //servidor.coneccion("localhost");
                        servidor.operacion("CREATE TABLE dinero(m50c float(10)," +
                                " m1 int(10), m2 int(10), m5 int(10), m10 int(10), m20 int(10), " +
                                " b20 int(10), b50 int(10), b100 int(10), b200 int(10)," +
                                " b500 int(10), b1000 int(10))");
                        servidor.operacion("INSERT INTO dinero values(0,0,0,0,0,0,0,0,0,0,0,0)");
                        JOptionPane.showMessageDialog(null, "SE CREO LA TABLA CORRECTAMENTE");
                        System.exit(0);
                 }
                else
                    System.exit(0);
            }
    }

    public void calcularTotal()
    {
          try {
            ServidorMysql servidor = new ServidorMysql();
            servidor.coneccion("localhost");
            servidor.consulta("select * from dinero");
            servidor.ConjuntoResultado.next();
            TOTAL = servidor.ConjuntoResultado.getInt("m50c") * 0.5;
            TOTAL += servidor.ConjuntoResultado.getInt("m1");
            TOTAL += servidor.ConjuntoResultado.getInt("m2") * 2;
            TOTAL += servidor.ConjuntoResultado.getInt("m5") * 5;
            TOTAL += servidor.ConjuntoResultado.getInt("m10") * 10;
            TOTAL += servidor.ConjuntoResultado.getInt("m20") * 20;
            TOTAL += servidor.ConjuntoResultado.getInt("b20") * 20;
            TOTAL += servidor.ConjuntoResultado.getInt("b50") * 50;
            TOTAL += servidor.ConjuntoResultado.getInt("b100") * 100;
            TOTAL += servidor.ConjuntoResultado.getInt("b200") * 200;
            TOTAL += servidor.ConjuntoResultado.getInt("b500") * 500;
            TOTAL += servidor.ConjuntoResultado.getInt("b1000") * 1000;
            jTextField1.setText(" $ "+TOTAL);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERROR AL CALCULAR TOTAL, REINICIE EL PROGRAMA POR FAVOR","ERROR",JOptionPane.ERROR_MESSAGE);

        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRO DE RETIROS");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("¿QUE DESEA HACER?");

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("INGRESO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton2.setText("RETIRO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton3.setText("CORTE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("CANTIDAD ACTUAL:");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Ingreso a = new Ingreso(this,true);
        a.setLocationRelativeTo(null);
        a.setVisible(true);
        calcularTotal();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Corte corte = new Corte(this,true);
        corte.setLocationRelativeTo(null);
        corte.setVisible(true);
        calcularTotal();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Retiro retirar = new Retiro(this,true);
       retirar.setLocationRelativeTo(null);
       retirar.setVisible(true);
       calcularTotal();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
       Principal ventana = new Principal();
       ventana.setLocationRelativeTo(null);
       ventana.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
