
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Retiro.java
 *
 * Created on 15/07/2010, 12:52:43 PM
 */

/**
 *
 * @author simpus
 */
public class Retiro extends javax.swing.JDialog {

    double TOTAL;
    DecimalFormat dosdigitos = new DecimalFormat("0.00");

    public void calcularTotal()
    {
       try
       {
           TOTAL = Integer.parseInt(jTextField13.getText()) * Double.parseDouble(jLabel2.getText());
           TOTAL+= Integer.parseInt(jTextField14.getText()) * Double.parseDouble(jLabel4.getText());
           TOTAL+= Integer.parseInt(jTextField15.getText()) * Double.parseDouble(jLabel17.getText());
           TOTAL+= Integer.parseInt(jTextField16.getText()) * Double.parseDouble(jLabel6.getText());
           TOTAL+= Integer.parseInt(jTextField17.getText()) * Double.parseDouble(jLabel7.getText());
           TOTAL+= Integer.parseInt(jTextField18.getText()) * Double.parseDouble(jLabel8.getText());

           TOTAL+= Integer.parseInt(jTextField19.getText()) * Double.parseDouble(jLabel10.getText());
           TOTAL+= Integer.parseInt(jTextField20.getText()) * Double.parseDouble(jLabel14.getText());
           TOTAL+= Integer.parseInt(jTextField21.getText()) * Double.parseDouble(jLabel19.getText());
           TOTAL+= Integer.parseInt(jTextField22.getText()) * Double.parseDouble(jLabel12.getText());
           TOTAL+= Integer.parseInt(jTextField23.getText()) * Double.parseDouble(jLabel9.getText());
           TOTAL+= Integer.parseInt(jTextField24.getText()) * Double.parseDouble(jLabel13.getText());
           jTextField25.setText("$ "+dosdigitos.format(TOTAL));
           jButton1.setEnabled(true);
       }
       catch(NumberFormatException e)
       {
           JOptionPane.showMessageDialog(null,"DEBE INTRODUCIR UNICAMENTE NUMEROS\n"+e,"ERROR DE FORMATO",JOptionPane.ERROR_MESSAGE);
           jButton1.setEnabled(false);

       }
    }
    public void Resto()
    {
        ServidorMysql resto = new ServidorMysql();
        resto.coneccion("localhost");
        resto.consulta("select * from dinero");
        try
        {
            resto.ConjuntoResultado.next();
            jTextField1.setText(resto.ConjuntoResultado.getString("m50c"));
            jTextField2.setText(resto.ConjuntoResultado.getString("m1"));
            jTextField3.setText(resto.ConjuntoResultado.getString("m2"));
            jTextField4.setText(resto.ConjuntoResultado.getString("m5"));
            jTextField5.setText(resto.ConjuntoResultado.getString("m10"));
            jTextField6.setText(resto.ConjuntoResultado.getString("m20"));
            jTextField12.setText(resto.ConjuntoResultado.getString("b20"));
            jTextField11.setText(resto.ConjuntoResultado.getString("b50"));
            jTextField7.setText(resto.ConjuntoResultado.getString("b100"));
            jTextField9.setText(resto.ConjuntoResultado.getString("b200"));
            jTextField8.setText(resto.ConjuntoResultado.getString("b500"));
            jTextField10.setText(resto.ConjuntoResultado.getString("b1000"));
        } catch (SQLException ex)
        {

        }
    }

    /** Creates new form Retiro */
    public Retiro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        calcularTotal();
        Resto();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RETIRO DE DINERO");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("2");

        jTextField3.setEditable(false);

        jTextField5.setEditable(false);

        jTextField4.setEditable(false);

        jTextField6.setEditable(false);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("10");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("0.5");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("MONEDAS");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("5");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("20");

        jTextField2.setEditable(false);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("1");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("N°");

        jTextField1.setEditable(false);

        jTextField13.setText("0");
        jTextField13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField13FocusLost(evt);
            }
        });

        jTextField14.setText("0");
        jTextField14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField14FocusLost(evt);
            }
        });

        jTextField15.setText("0");
        jTextField15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField15FocusLost(evt);
            }
        });

        jTextField16.setText("0");
        jTextField16.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField16FocusLost(evt);
            }
        });

        jTextField17.setText("0");
        jTextField17.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField17FocusLost(evt);
            }
        });

        jTextField18.setText("0");
        jTextField18.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField18FocusLost(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Retiro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField13, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                        .addComponent(jTextField14, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField18)
                                        .addComponent(jTextField17)
                                        .addComponent(jTextField16)
                                        .addComponent(jTextField15, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))))
                            .addGap(18, 18, 18)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("100");

        jTextField7.setEditable(false);

        jTextField8.setEditable(false);

        jTextField9.setEditable(false);

        jTextField10.setEditable(false);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("500");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("20");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("BILLETES");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("200");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("1000");

        jTextField11.setEditable(false);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("50");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("N°");

        jTextField12.setEditable(false);

        jTextField19.setText("0");
        jTextField19.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField19FocusLost(evt);
            }
        });

        jTextField20.setText("0");
        jTextField20.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField20FocusLost(evt);
            }
        });

        jTextField21.setText("0");
        jTextField21.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField21FocusLost(evt);
            }
        });

        jTextField22.setText("0");
        jTextField22.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField22FocusLost(evt);
            }
        });

        jTextField23.setText("0");
        jTextField23.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField23FocusLost(evt);
            }
        });

        jTextField24.setText("0");
        jTextField24.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField24FocusLost(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Retiro");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField19, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                        .addComponent(jTextField20, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField24)
                                        .addComponent(jTextField23)
                                        .addComponent(jTextField22)
                                        .addComponent(jTextField21, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))))
                            .addGap(18, 18, 18)))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Cantidad total a retirar");

        jTextField25.setEditable(false);
        jTextField25.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextField25.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("<HTML>INGRESA EL NÚMERO DE MONEDAS Y BILLETES QUE SE <BR>RETIRARÁN");

        jButton1.setText("RETIRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField13FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField13FocusLost
        if(jTextField13.getText().compareTo("")==0)
            jTextField13.setText("0");

        try
        {
            if(Integer.parseInt(jTextField13.getText()) > Integer.parseInt(jTextField1.getText())){
                 jTextField13.setText("0");
                 JOptionPane.showMessageDialog(null,"NO HAY SUFICIENTES MONEDAS","ERROR DE INSUFICIENCIA",JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        catch(NumberFormatException e){
            jTextField13.setText("0");
            JOptionPane.showMessageDialog(null,"DEBE INTRODUCIR UNICAMENTE NUMEROS\n","ERROR DE FORMATO",JOptionPane.ERROR_MESSAGE);
            return;
        }
        calcularTotal();
    }//GEN-LAST:event_jTextField13FocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField14FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField14FocusLost
        if(jTextField14.getText().compareTo("")==0)
            jTextField14.setText("0");

        try
        {
            if(Integer.parseInt(jTextField14.getText()) > Integer.parseInt(jTextField2.getText())){
                 jTextField14.setText("0");
                 JOptionPane.showMessageDialog(null,"NO HAY SUFICIENTES MONEDAS","ERROR DE INSUFICIENCIA",JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        catch(NumberFormatException e){
            jTextField14.setText("0");
            JOptionPane.showMessageDialog(null,"DEBE INTRODUCIR UNICAMENTE NUMEROS\n","ERROR DE FORMATO",JOptionPane.ERROR_MESSAGE);
            return;
        }
        calcularTotal();
    }//GEN-LAST:event_jTextField14FocusLost

    private void jTextField15FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField15FocusLost
        if(jTextField15.getText().compareTo("")==0)
            jTextField15.setText("0");

        try
        {
            if(Integer.parseInt(jTextField15.getText()) > Integer.parseInt(jTextField3.getText())){
                 jTextField15.setText("0");
                 JOptionPane.showMessageDialog(null,"NO HAY SUFICIENTES MONEDAS","ERROR DE INSUFICIENCIA",JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        catch(NumberFormatException e){
            jTextField15.setText("0");
            JOptionPane.showMessageDialog(null,"DEBE INTRODUCIR UNICAMENTE NUMEROS\n","ERROR DE FORMATO",JOptionPane.ERROR_MESSAGE);
            return;
        }
        calcularTotal();
    }//GEN-LAST:event_jTextField15FocusLost

    private void jTextField16FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField16FocusLost
        if(jTextField16.getText().compareTo("")==0)
            jTextField16.setText("0");

        try
        {
            if(Integer.parseInt(jTextField16.getText()) > Integer.parseInt(jTextField4.getText())){
                 jTextField16.setText("0");
                 JOptionPane.showMessageDialog(null,"NO HAY SUFICIENTES MONEDAS","ERROR DE INSUFICIENCIA",JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        catch(NumberFormatException e){
            jTextField16.setText("0");
            JOptionPane.showMessageDialog(null,"DEBE INTRODUCIR UNICAMENTE NUMEROS\n","ERROR DE FORMATO",JOptionPane.ERROR_MESSAGE);
            return;
        }
        calcularTotal();
    }//GEN-LAST:event_jTextField16FocusLost

    private void jTextField17FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField17FocusLost
        if(jTextField17.getText().compareTo("")==0)
            jTextField17.setText("0");

        try
        {
            if(Integer.parseInt(jTextField17.getText()) > Integer.parseInt(jTextField5.getText())){
                 jTextField17.setText("0");
                 JOptionPane.showMessageDialog(null,"NO HAY SUFICIENTES MONEDAS","ERROR DE INSUFICIENCIA",JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        catch(NumberFormatException e){
            jTextField17.setText("0");
            JOptionPane.showMessageDialog(null,"DEBE INTRODUCIR UNICAMENTE NUMEROS\n","ERROR DE FORMATO",JOptionPane.ERROR_MESSAGE);
            return;
        }
        calcularTotal();
    }//GEN-LAST:event_jTextField17FocusLost

    private void jTextField18FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField18FocusLost
       if(jTextField18.getText().compareTo("")==0)
            jTextField18.setText("0");

        try
        {
            if(Integer.parseInt(jTextField18.getText()) > Integer.parseInt(jTextField6.getText())){
                 jTextField18.setText("0");
                 JOptionPane.showMessageDialog(null,"NO HAY SUFICIENTES MONEDAS","ERROR DE INSUFICIENCIA",JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        catch(NumberFormatException e){
            jTextField18.setText("0");
            JOptionPane.showMessageDialog(null,"DEBE INTRODUCIR UNICAMENTE NUMEROS\n","ERROR DE FORMATO",JOptionPane.ERROR_MESSAGE);
            return;
        }
        calcularTotal();
    }//GEN-LAST:event_jTextField18FocusLost

    private void jTextField19FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField19FocusLost
        if(jTextField19.getText().compareTo("")==0)
            jTextField19.setText("0");

        try
        {
            if(Integer.parseInt(jTextField19.getText()) > Integer.parseInt(jTextField12.getText())){
                 jTextField19.setText("0");
                 JOptionPane.showMessageDialog(null,"NO HAY SUFICIENTES BILLETES","ERROR DE INSUFICIENCIA",JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        catch(NumberFormatException e){
            jTextField19.setText("0");
            JOptionPane.showMessageDialog(null,"DEBE INTRODUCIR UNICAMENTE NUMEROS\n","ERROR DE FORMATO",JOptionPane.ERROR_MESSAGE);
            return;
        }
        calcularTotal();
    }//GEN-LAST:event_jTextField19FocusLost

    private void jTextField20FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField20FocusLost
        if(jTextField20.getText().compareTo("")==0)
            jTextField20.setText("0");

        try
        {
            if(Integer.parseInt(jTextField20.getText()) > Integer.parseInt(jTextField11.getText())){
                 jTextField20.setText("0");
                 JOptionPane.showMessageDialog(null,"NO HAY SUFICIENTES BILLETES","ERROR DE INSUFICIENCIA",JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        catch(NumberFormatException e){
            jTextField20.setText("0");
            JOptionPane.showMessageDialog(null,"DEBE INTRODUCIR UNICAMENTE NUMEROS\n","ERROR DE FORMATO",JOptionPane.ERROR_MESSAGE);
            return;
        }
        calcularTotal();
    }//GEN-LAST:event_jTextField20FocusLost

    private void jTextField21FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField21FocusLost
        if(jTextField21.getText().compareTo("")==0)
            jTextField21.setText("0");

        try
        {
            if(Integer.parseInt(jTextField21.getText()) > Integer.parseInt(jTextField7.getText())){
                 jTextField21.setText("0");
                 JOptionPane.showMessageDialog(null,"NO HAY SUFICIENTES BILLETES","ERROR DE INSUFICIENCIA",JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        catch(NumberFormatException e){
            jTextField21.setText("0");
            JOptionPane.showMessageDialog(null,"DEBE INTRODUCIR UNICAMENTE NUMEROS\n","ERROR DE FORMATO",JOptionPane.ERROR_MESSAGE);
            return;
        }
        calcularTotal();
    }//GEN-LAST:event_jTextField21FocusLost

    private void jTextField22FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField22FocusLost
        if(jTextField22.getText().compareTo("")==0)
            jTextField22.setText("0");

        try
        {
            if(Integer.parseInt(jTextField22.getText()) > Integer.parseInt(jTextField9.getText())){
                 jTextField22.setText("0");
                 JOptionPane.showMessageDialog(null,"NO HAY SUFICIENTES BILLETES","ERROR DE INSUFICIENCIA",JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        catch(NumberFormatException e){
            jTextField22.setText("0");
            JOptionPane.showMessageDialog(null,"DEBE INTRODUCIR UNICAMENTE NUMEROS\n","ERROR DE FORMATO",JOptionPane.ERROR_MESSAGE);
            return;
        }
        calcularTotal();
    }//GEN-LAST:event_jTextField22FocusLost

    private void jTextField23FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField23FocusLost
        if(jTextField23.getText().compareTo("")==0)
            jTextField23.setText("0");

        try
        {
            if(Integer.parseInt(jTextField23.getText()) > Integer.parseInt(jTextField8.getText())){
                 jTextField23.setText("0");
                 JOptionPane.showMessageDialog(null,"NO HAY SUFICIENTES BILLETES","ERROR DE INSUFICIENCIA",JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        catch(NumberFormatException e){
            jTextField23.setText("0");
            JOptionPane.showMessageDialog(null,"DEBE INTRODUCIR UNICAMENTE NUMEROS\n","ERROR DE FORMATO",JOptionPane.ERROR_MESSAGE);
            return;
        }
        calcularTotal();
    }//GEN-LAST:event_jTextField23FocusLost

    private void jTextField24FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField24FocusLost
        if(jTextField24.getText().compareTo("")==0)
            jTextField24.setText("0");

        try
        {
            if(Integer.parseInt(jTextField24.getText()) > Integer.parseInt(jTextField10.getText())){
                 jTextField24.setText("0");
                 JOptionPane.showMessageDialog(null,"NO HAY SUFICIENTES BILLETES","ERROR DE INSUFICIENCIA",JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        catch(NumberFormatException e){
            jTextField24.setText("0");
            JOptionPane.showMessageDialog(null,"DEBE INTRODUCIR UNICAMENTE NUMEROS\n","ERROR DE FORMATO",JOptionPane.ERROR_MESSAGE);
            return;
        }
        calcularTotal();
    }//GEN-LAST:event_jTextField24FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿ESTA SEGURO QUE DESEA RETIRAR "+ jTextField25.getText() +" PESOS?","ADVERTENCIA",JOptionPane.YES_NO_OPTION);
        if(respuesta == JOptionPane.YES_OPTION)
        {
            ServidorMysql ingreso = new ServidorMysql();
            ingreso.coneccion("localhost");
            ingreso.consulta("Select * from dinero");
            try {
                ingreso.ConjuntoResultado.next();
                ingreso.operacion("update dinero set m50c = "+(ingreso.ConjuntoResultado.getInt("m50c")- Integer.parseInt(jTextField13.getText())));
                ingreso.operacion("update dinero set m1 = "+(ingreso.ConjuntoResultado.getInt("m1")- Integer.parseInt(jTextField14.getText())));
                ingreso.operacion("update dinero set m2 = "+(ingreso.ConjuntoResultado.getInt("m2")- Integer.parseInt(jTextField15.getText())));
                ingreso.operacion("update dinero set m5 = "+(ingreso.ConjuntoResultado.getInt("m5")- Integer.parseInt(jTextField16.getText())));
                ingreso.operacion("update dinero set m10 = "+(ingreso.ConjuntoResultado.getInt("m10")- Integer.parseInt(jTextField17.getText())));
                ingreso.operacion("update dinero set m20 = "+(ingreso.ConjuntoResultado.getInt("m20")- Integer.parseInt(jTextField18.getText())));
                
                ingreso.operacion("update dinero set b20 = "+(ingreso.ConjuntoResultado.getInt("b20")- Integer.parseInt(jTextField19.getText())));
                ingreso.operacion("update dinero set b50 = "+(ingreso.ConjuntoResultado.getInt("b50")- Integer.parseInt(jTextField20.getText())));
                ingreso.operacion("update dinero set b100 = "+(ingreso.ConjuntoResultado.getInt("b100")- Integer.parseInt(jTextField21.getText())));
                ingreso.operacion("update dinero set b200 = "+(ingreso.ConjuntoResultado.getInt("b200")- Integer.parseInt(jTextField22.getText())));
                ingreso.operacion("update dinero set b500 = "+(ingreso.ConjuntoResultado.getInt("b500")- Integer.parseInt(jTextField23.getText())));
                ingreso.operacion("update dinero set b1000 = "+(ingreso.ConjuntoResultado.getInt("b1000")- Integer.parseInt(jTextField24.getText())));
                dispose();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"ERROR EN LA BASE DE DATOS\n","ERROR",JOptionPane.ERROR_MESSAGE);
            }
        }
        else
            return;
    }//GEN-LAST:event_jButton1ActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

}
